-- AlterTable
ALTER TABLE "Enrollment" ADD COLUMN     "enrolled" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "id" DROP NOT NULL,
ALTER COLUMN "user_id" DROP NOT NULL,
ALTER COLUMN "expired" DROP NOT NULL,
ALTER COLUMN "is_free_trial" DROP NOT NULL,
ALTER COLUMN "completed" DROP NOT NULL;
