-- CreateTable
CREATE TABLE "MobilizerCode" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "isAvailable" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MobilizerCode_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "MobilizerCode_code_key" ON "MobilizerCode"("code");

-- CreateIndex
CREATE INDEX "MobilizerCode_code_idx" ON "MobilizerCode"("code");

-- CreateIndex
CREATE INDEX "MobilizerCode_isAvailable_idx" ON "MobilizerCode"("isAvailable");

-- Insert initial mobilizer codes
INSERT INTO "MobilizerCode" ("id", "code", "isAvailable", "createdAt", "updatedAt") VALUES
('cm1', 'GENDEI', true, NOW(), NOW()),
('cm2', 'MUB', true, NOW(), NOW()),
('cm3', 'ARO', true, NOW(), NOW()),
('cm4', 'GIDN', true, NOW(), NOW()),
('cm5', 'WIN', true, NOW(), NOW()),
('cm6', 'NRCS01', true, NOW(), NOW()),
('cm7', 'KSUG02', true, NOW(), NOW()),
('cm8', 'NYSC', true, NOW(), NOW()),
('cm9', 'Dasia23', true, NOW(), NOW()),
('cm10', 'RCCGDD', true, NOW(), NOW()),
('cm11', 'KEN01', true, NOW(), NOW()),
('cm12', 'WOMDEV', true, NOW(), NOW()),
('cm13', 'LANMO', true, NOW(), NOW()),
('cm14', 'AKIN T', true, NOW(), NOW()),
('cm15', 'GOKE19', true, NOW(), NOW()),
('cm16', 'OLUFEMISAMSON', true, NOW(), NOW()),
('cm17', 'Pearl', true, NOW(), NOW()),
('cm18', 'OGJLE05', true, NOW(), NOW()),
('cm19', 'ADEOLU', true, NOW(), NOW()),
('cm20', 'NAFOGUN', true, NOW(), NOW()),
('cm21', 'KENNYWISE', true, NOW(), NOW()),
('cm22', 'DATARAIN', true, NOW(), NOW()),
('cm23', 'TK001', true, NOW(), NOW()),
('cm24', 'TK002', true, NOW(), NOW()),
('cm25', 'TK003', true, NOW(), NOW()),
('cm26', 'TK004', true, NOW(), NOW()),
('cm27', 'TK005', true, NOW(), NOW()),
('cm28', 'TK006', true, NOW(), NOW()),
('cm29', 'TK007', true, NOW(), NOW()),
('cm30', 'TK008', true, NOW(), NOW()),
('cm31', 'TK009', true, NOW(), NOW()),
('cm32', 'NrsVee', true, NOW(), NOW()),
('cm33', 'TK010', true, NOW(), NOW()),
('cm34', 'TK011', true, NOW(), NOW()),
('cm35', 'TK012', true, NOW(), NOW()),
('cm36', 'TK013', true, NOW(), NOW()),
('cm37', 'TK014', true, NOW(), NOW()),
('cm38', 'TK015', true, NOW(), NOW()),
('cm39', 'TK016', true, NOW(), NOW()),
('cm40', 'TK017', true, NOW(), NOW()),
('cm41', 'TK018', true, NOW(), NOW()),
('cm42', 'TK019', true, NOW(), NOW()),
('cm43', 'TK020', true, NOW(), NOW()),
('cm44', 'TK021', true, NOW(), NOW()),
('cm45', 'TK022', true, NOW(), NOW()),
('cm46', 'TK023', true, NOW(), NOW()),
('cm47', 'TK024', true, NOW(), NOW()),
('cm48', 'TK025', true, NOW(), NOW()),
('cm49', 'TK026', true, NOW(), NOW()),
('cm50', 'TK027', true, NOW(), NOW()),
('cm51', 'TK028', true, NOW(), NOW()),
('cm52', 'TK029', true, NOW(), NOW()),
('cm53', 'TK030', true, NOW(), NOW()),
('cm54', 'TK031', true, NOW(), NOW()),
('cm55', 'TK032', true, NOW(), NOW()),
('cm56', 'TK033', true, NOW(), NOW()),
('cm57', 'TK034', true, NOW(), NOW()),
('cm58', 'TK035', true, NOW(), NOW()),
('cm59', 'E-SRCOE', true, NOW(), NOW()),
('cm60', 'H-SRCOE', true, NOW(), NOW()),
('cm61', 'UPSKILL', true, NOW(), NOW()),
('cm62', 'LG/LO/003', true, NOW(), NOW()),
('cm63', 'LG/VA/007', true, NOW(), NOW()),
('cm64', 'LG/EC/011', true, NOW(), NOW()),
('cm65', 'AZMUSIK', true, NOW(), NOW()),
('cm66', 'LASU', true, NOW(), NOW()),
('cm67', 'JAM', true, NOW(), NOW()),
('cm68', 'NATH', true, NOW(), NOW()),
('cm69', 'EMM', true, NOW(), NOW()),
('cm70', 'MATT', true, NOW(), NOW()),
('cm71', 'MAPOLY', true, NOW(), NOW()),
('cm72', 'FCOC', true, NOW(), NOW()),
('cm73', 'DPRINCE', true, NOW(), NOW()),
('cm74', 'ITL', true, NOW(), NOW()),
('cm75', 'PJF', true, NOW(), NOW()),
('cm76', 'GENDI', true, NOW(), NOW()),
('cm77', 'ACO', true, NOW(), NOW()),
('cm78', 'COMMONWEALTH', true, NOW(), NOW()),
('cm79', 'SPRING', true, NOW(), NOW()),
('cm80', 'N-NYSC', true, NOW(), NOW()),
('cm81', 'Bright- TKC', true, NOW(), NOW()),
('cm82', 'Ige', true, NOW(), NOW()),
('cm83', 'ELS', true, NOW(), NOW()),
('cm84', 'TIM', true, NOW(), NOW()),
('cm85', 'EDU', true, NOW(), NOW()),
('cm86', 'FAS', true, NOW(), NOW()),
('cm87', 'KLICK', true, NOW(), NOW()),
('cm88', 'FSS', true, NOW(), NOW()),
('cm89', 'AAA', true, NOW(), NOW()),
('cm90', 'JON', true, NOW(), NOW()),
('cm91', 'CENTS', true, NOW(), NOW()),
('cm92', 'DREAMCODE', true, NOW(), NOW()),
('cm93', 'R-L', true, NOW(), NOW()),
('cm94', 'CHO', true, NOW(), NOW()),
('cm95', 'RERE', true, NOW(), NOW()),
('cm96', 'ELPIS', true, NOW(), NOW()),
('cm97', 'O-NYSC', true, NOW(), NOW()),
('cm98', 'TFN', true, NOW(), NOW()),
('cm99', 'LASUED-TA', true, NOW(), NOW()),
('cm100', 'LASUED-FA', true, NOW(), NOW()),
('cm101', 'LASUED-M', true, NOW(), NOW()),
('cm102', 'emmygrace', true, NOW(), NOW()),
('cm103', 'ADCN', true, NOW(), NOW()),
('cm104', 'ZEAL', true, NOW(), NOW()),
('cm105', 'Uchenna', true, NOW(), NOW()),
('cm106', 'LAG-01', true, NOW(), NOW()),
('cm107', 'ABIM', true, NOW(), NOW()),
('cm108', 'TPLP', true, NOW(), NOW()),
('cm109', 'Lexxie01', true, NOW(), NOW()),
('cm110', 'YASUG', true, NOW(), NOW()),
('cm111', 'FASA', true, NOW(), NOW()),
('cm112', 'Lola Tafta', true, NOW(), NOW()),
('cm113', 'Coach Ayanfe', true, NOW(), NOW()),
('cm114', 'ARA', true, NOW(), NOW()),
('cm115', 'E-NYSC', true, NOW(), NOW()),
('cm116', 'OD-NYSC', true, NOW(), NOW()),
('cm117', 'SARCO', true, NOW(), NOW()),
('cm118', 'YERKS KANO', true, NOW(), NOW()),
('cm119', 'YERKS LAGOS', true, NOW(), NOW()),
('cm120', 'YERKS OGUN', true, NOW(), NOW()),
('cm121', 'JULIET', true, NOW(), NOW()),
('cm122', 'BESTM25', true, NOW(), NOW()),
('cm123', 'LOWAN', true, NOW(), NOW()),
('cm124', 'GOD1', true, NOW(), NOW()),
('cm125', 'AAALA', true, NOW(), NOW()),
('cm126', 'NYCN Ibeju', true, NOW(), NOW());
